# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1058)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QFrame {\n"
"    border-radius : 5px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    background-color : rgb(240, 240, 240);\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border-radius : 3px;\n"
"    background-color : rgb(120, 120, 120);\n"
"}\n"
"\n"
"QListView {\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius : 5px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    background-color : white;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-radius : 3px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    background-color: rgb(180, 180, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-radius : 3px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: black;\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QLabel {\n"
"    border-width : 0px;\n"
"}\n"
"\n"
"Line {\n"
"    border-width : 0px;\n"
"    color : black;\n"
"}\n"
"\n"
"\n"
"QSpinBox {\n"
"    border-radius : 5px;\n"
"    border: 1px solid black;\n"
"    background-color : white; \n"
"    color : black;\n"
"    padding-left : 15px;\n"
"    padding-right : 15px;\n"
"    max-height: 22px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QSpinBox QLineEdit {\n"
"    text-align: center;\n"
"}\n"
"\n"
"QSpinBox QAbstractSpinBox {\n"
"    text-align: center;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: center right; \n"
"border-image: url(:/icons/arrow-right.png);\n"
"border-color: black;\n"
"border : 1px;\n"
"right : 5px;\n"
"width : 5px;\n"
"}\n"
"\n"
"QSpinBox::up-button::pressed {\n"
"border-image: url(:/icons/arrow-right-pressed.png);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: center left ;\n"
"border-image: url(:/icons/arrow-left.png);\n"
"border-color: black;\n"
"border : 1px;\n"
"left : 5px;\n"
"width : 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button::pressed {\n"
"border-image: url(:/icons/arrow-left-pressed.png);\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius : 5px;\n"
"    border : 1px solid black;\n"
"    background-color : white;\n"
"    color : black;\n"
"    padding-right : 20px;\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    padding-right : 10px;\n"
"    image: url(:/icons/arrow-down.png);\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QComboBox::drop-down::pressed {\n"
"    padding-right : 10px;\n"
"    image: url(:/icons/arrow-down-pressed.png);\n"
"    min-width: 25px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color : black;\n"
"    background-color : white;\n"
"    border-radius : 5px;\n"
"    border : 1px solid black;\n"
"    outline : 0px;\n"
"    selection-background-color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView QScrollBar:vertical {\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView QScrollBar::handle:vertical {\n"
"  background-color: white;\n"
"  border : 3px solid black;\n"
"  border-radius : 5px;\n"
"  color: black;\n"
"  max-width : 5px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView QScrollBar::add-page:vertical {\n"
"    background: none;\n"
"    height : 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    height : 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView QScrollBar::add-line:vertical {\n"
"    background: none;\n"
"    height : 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    height : 0px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    color: white;\n"
"     border: 1px solid black;\n"
"     border-radius: 5px;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: black;\n"
"     width: 2px;\n"
" }\n"
"\n"
"QLineEdit {\n"
"    border-radius: 5px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftFrame = QtWidgets.QFrame(self.centralwidget)
        self.LeftFrame.setMinimumSize(QtCore.QSize(260, 0))
        self.LeftFrame.setMaximumSize(QtCore.QSize(260, 16777215))
        self.LeftFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftFrame.setObjectName("LeftFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.LeftFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LeftFrameVerticalLayout = QtWidgets.QVBoxLayout()
        self.LeftFrameVerticalLayout.setSpacing(15)
        self.LeftFrameVerticalLayout.setObjectName("LeftFrameVerticalLayout")
        self.LogoFrame = QtWidgets.QFrame(self.LeftFrame)
        self.LogoFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.LogoFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.LogoFrame.setStyleSheet("QFrame {\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.LogoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LogoFrame.setObjectName("LogoFrame")
        self.label_19 = QtWidgets.QLabel(self.LogoFrame)
        self.label_19.setGeometry(QtCore.QRect(30, 20, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.LeftFrameVerticalLayout.addWidget(self.LogoFrame)
        self.AnswerModelFrame = QtWidgets.QFrame(self.LeftFrame)
        self.AnswerModelFrame.setMinimumSize(QtCore.QSize(0, 240))
        self.AnswerModelFrame.setMaximumSize(QtCore.QSize(16777215, 330))
        self.AnswerModelFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AnswerModelFrame.setObjectName("AnswerModelFrame")
        self.AnswerModelContextTokensSpinBox = QtWidgets.QSpinBox(self.AnswerModelFrame)
        self.AnswerModelContextTokensSpinBox.setGeometry(QtCore.QRect(150, 90, 81, 24))
        self.AnswerModelContextTokensSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnswerModelContextTokensSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.AnswerModelContextTokensSpinBox.setMinimum(500)
        self.AnswerModelContextTokensSpinBox.setMaximum(9000)
        self.AnswerModelContextTokensSpinBox.setSingleStep(500)
        self.AnswerModelContextTokensSpinBox.setProperty("value", 1000)
        self.AnswerModelContextTokensSpinBox.setObjectName("AnswerModelContextTokensSpinBox")
        self.label_2 = QtWidgets.QLabel(self.AnswerModelFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.AnswerModelFrame)
        self.label_3.setGeometry(QtCore.QRect(10, 125, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.AnswerModelThreadsSpinBox = QtWidgets.QSpinBox(self.AnswerModelFrame)
        self.AnswerModelThreadsSpinBox.setGeometry(QtCore.QRect(150, 125, 81, 24))
        self.AnswerModelThreadsSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.AnswerModelThreadsSpinBox.setMinimum(1)
        self.AnswerModelThreadsSpinBox.setMaximum(128)
        self.AnswerModelThreadsSpinBox.setObjectName("AnswerModelThreadsSpinBox")
        self.label_4 = QtWidgets.QLabel(self.AnswerModelFrame)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.AnswerModelGPULayersSpinBox = QtWidgets.QSpinBox(self.AnswerModelFrame)
        self.AnswerModelGPULayersSpinBox.setGeometry(QtCore.QRect(150, 160, 81, 24))
        self.AnswerModelGPULayersSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.AnswerModelGPULayersSpinBox.setMaximum(100)
        self.AnswerModelGPULayersSpinBox.setObjectName("AnswerModelGPULayersSpinBox")
        self.AnswerModelComboBox = QtWidgets.QComboBox(self.AnswerModelFrame)
        self.AnswerModelComboBox.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.AnswerModelComboBox.setObjectName("AnswerModelComboBox")
        self.AnswerModelLoadPushButton = QtWidgets.QPushButton(self.AnswerModelFrame)
        self.AnswerModelLoadPushButton.setGeometry(QtCore.QRect(10, 200, 221, 26))
        self.AnswerModelLoadPushButton.setObjectName("AnswerModelLoadPushButton")
        self.AnswerModelTitle = QtWidgets.QFrame(self.AnswerModelFrame)
        self.AnswerModelTitle.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.AnswerModelTitle.setMinimumSize(QtCore.QSize(0, 31))
        self.AnswerModelTitle.setMaximumSize(QtCore.QSize(16777215, 31))
        self.AnswerModelTitle.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.AnswerModelTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AnswerModelTitle.setObjectName("AnswerModelTitle")
        self.label = QtWidgets.QLabel(self.AnswerModelTitle)
        self.label.setGeometry(QtCore.QRect(10, -3, 141, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.LeftFrameVerticalLayout.addWidget(self.AnswerModelFrame)
        self.GenerationSettingsFrame = QtWidgets.QFrame(self.LeftFrame)
        self.GenerationSettingsFrame.setMinimumSize(QtCore.QSize(0, 140))
        self.GenerationSettingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GenerationSettingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GenerationSettingsFrame.setObjectName("GenerationSettingsFrame")
        self.GenerationSettingsTitle = QtWidgets.QFrame(self.GenerationSettingsFrame)
        self.GenerationSettingsTitle.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.GenerationSettingsTitle.setMinimumSize(QtCore.QSize(0, 31))
        self.GenerationSettingsTitle.setMaximumSize(QtCore.QSize(16777215, 31))
        self.GenerationSettingsTitle.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.GenerationSettingsTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.GenerationSettingsTitle.setObjectName("GenerationSettingsTitle")
        self.label_22 = QtWidgets.QLabel(self.GenerationSettingsTitle)
        self.label_22.setGeometry(QtCore.QRect(5, -1, 181, 36))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.GenerationSettingsEchoCheckBox = QtWidgets.QCheckBox(self.GenerationSettingsFrame)
        self.GenerationSettingsEchoCheckBox.setGeometry(QtCore.QRect(55, 110, 21, 21))
        self.GenerationSettingsEchoCheckBox.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/icons/check-box-unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image: url(:/icons/check-box-unchecked-pressed.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image: url(:/icons/check-box-unchecked-pressed.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icons/check-box-checked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image: url(:/icons/check-box-checked-pressed.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    image: url(:/icons/check-box-checked-pressed.png);\n"
"}")
        self.GenerationSettingsEchoCheckBox.setText("")
        self.GenerationSettingsEchoCheckBox.setChecked(False)
        self.GenerationSettingsEchoCheckBox.setTristate(False)
        self.GenerationSettingsEchoCheckBox.setObjectName("GenerationSettingsEchoCheckBox")
        self.GenerationSettingsTopKSpinBox = QtWidgets.QSpinBox(self.GenerationSettingsFrame)
        self.GenerationSettingsTopKSpinBox.setGeometry(QtCore.QRect(145, 75, 81, 24))
        self.GenerationSettingsTopKSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.GenerationSettingsTopKSpinBox.setObjectName("GenerationSettingsTopKSpinBox")
        self.label_5 = QtWidgets.QLabel(self.GenerationSettingsFrame)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.GenerationSettingsFrame)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.GenerationSettingsMaxTokensSpinBox = QtWidgets.QSpinBox(self.GenerationSettingsFrame)
        self.GenerationSettingsMaxTokensSpinBox.setGeometry(QtCore.QRect(145, 40, 81, 24))
        self.GenerationSettingsMaxTokensSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.GenerationSettingsMaxTokensSpinBox.setMinimum(200)
        self.GenerationSettingsMaxTokensSpinBox.setMaximum(9999)
        self.GenerationSettingsMaxTokensSpinBox.setSingleStep(100)
        self.GenerationSettingsMaxTokensSpinBox.setObjectName("GenerationSettingsMaxTokensSpinBox")
        self.label_6 = QtWidgets.QLabel(self.GenerationSettingsFrame)
        self.label_6.setGeometry(QtCore.QRect(10, 75, 101, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.GenerationSettingsTitle.raise_()
        self.GenerationSettingsTopKSpinBox.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.GenerationSettingsMaxTokensSpinBox.raise_()
        self.label_6.raise_()
        self.GenerationSettingsEchoCheckBox.raise_()
        self.LeftFrameVerticalLayout.addWidget(self.GenerationSettingsFrame)
        self.PresetFrame = QtWidgets.QFrame(self.LeftFrame)
        self.PresetFrame.setMinimumSize(QtCore.QSize(0, 300))
        self.PresetFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PresetFrame.setObjectName("PresetFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.PresetFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.PresetTitle = QtWidgets.QFrame(self.PresetFrame)
        self.PresetTitle.setMinimumSize(QtCore.QSize(0, 31))
        self.PresetTitle.setMaximumSize(QtCore.QSize(16777215, 31))
        self.PresetTitle.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.PresetTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PresetTitle.setObjectName("PresetTitle")
        self.label_8 = QtWidgets.QLabel(self.PresetTitle)
        self.label_8.setGeometry(QtCore.QRect(5, -1, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.PresetTitle, 0, 0, 1, 1)
        self.PresetVerticalLayout = QtWidgets.QVBoxLayout()
        self.PresetVerticalLayout.setContentsMargins(6, 6, 6, 6)
        self.PresetVerticalLayout.setObjectName("PresetVerticalLayout")
        self.PresetComboBox = QtWidgets.QComboBox(self.PresetFrame)
        self.PresetComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.PresetComboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.PresetComboBox.setObjectName("PresetComboBox")
        self.PresetVerticalLayout.addWidget(self.PresetComboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.PresetVerticalLayout.addItem(spacerItem)
        self.PresetTextEdit = QtWidgets.QTextEdit(self.PresetFrame)
        self.PresetTextEdit.setObjectName("PresetTextEdit")
        self.PresetVerticalLayout.addWidget(self.PresetTextEdit)
        self.gridLayout_4.addLayout(self.PresetVerticalLayout, 1, 0, 1, 1)
        self.LeftFrameVerticalLayout.addWidget(self.PresetFrame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.LeftFrameVerticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.LeftFrameVerticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.LeftFrame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setMinimumSize(QtCore.QSize(800, 800))
        self.frame_9.setMaximumSize(QtCore.QSize(1000, 800))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setHorizontalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listView = QtWidgets.QListView(self.frame_9)
        self.listView.setObjectName("listView")
        self.gridLayout_5.addWidget(self.listView, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.PromptTextFrame = QtWidgets.QFrame(self.centralwidget)
        self.PromptTextFrame.setMinimumSize(QtCore.QSize(800, 150))
        self.PromptTextFrame.setMaximumSize(QtCore.QSize(1000, 150))
        self.PromptTextFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PromptTextFrame.setObjectName("PromptTextFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.PromptTextFrame)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PromptTextEdit = QtWidgets.QTextEdit(self.PromptTextFrame)
        self.PromptTextEdit.setObjectName("PromptTextEdit")
        self.horizontalLayout_3.addWidget(self.PromptTextEdit)
        self.PromptButtons = QtWidgets.QFrame(self.PromptTextFrame)
        self.PromptButtons.setMinimumSize(QtCore.QSize(70, 0))
        self.PromptButtons.setMaximumSize(QtCore.QSize(60, 16777215))
        self.PromptButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PromptButtons.setObjectName("PromptButtons")
        self.PromptSendPushButton = QtWidgets.QPushButton(self.PromptButtons)
        self.PromptSendPushButton.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.PromptSendPushButton.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/send.png);\n"
"    padding: 10px 10px 10px 10px;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    image: url(:/icons/send-pressed.png);\n"
"    padding: 10px 10px 10px 10px;\n"
"}")
        self.PromptSendPushButton.setText("")
        self.PromptSendPushButton.setObjectName("PromptSendPushButton")
        self.PromptStopPushButon = QtWidgets.QPushButton(self.PromptButtons)
        self.PromptStopPushButon.setGeometry(QtCore.QRect(10, 70, 51, 51))
        self.PromptStopPushButon.setStyleSheet("QPushButton {\n"
"    image: url(:/icons/stop.png);\n"
"    padding: 10px 10px 10px 10px;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    image: url(:/icons/stop-pressed.png);\n"
"    padding: 10px 10px 10px 10px;\n"
"}")
        self.PromptStopPushButon.setText("")
        self.PromptStopPushButon.setObjectName("PromptStopPushButon")
        self.horizontalLayout_3.addWidget(self.PromptButtons)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.PromptTextFrame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(260, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(260, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TextProcessingFrame = QtWidgets.QFrame(self.frame_2)
        self.TextProcessingFrame.setMinimumSize(QtCore.QSize(0, 150))
        self.TextProcessingFrame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.TextProcessingFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TextProcessingFrame.setObjectName("TextProcessingFrame")
        self.label_10 = QtWidgets.QLabel(self.TextProcessingFrame)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 101, 26))
        self.label_10.setObjectName("label_10")
        self.TextProcessingChunkSizeSpinBox = QtWidgets.QSpinBox(self.TextProcessingFrame)
        self.TextProcessingChunkSizeSpinBox.setGeometry(QtCore.QRect(140, 40, 91, 24))
        self.TextProcessingChunkSizeSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TextProcessingChunkSizeSpinBox.setMinimum(100)
        self.TextProcessingChunkSizeSpinBox.setMaximum(2000)
        self.TextProcessingChunkSizeSpinBox.setSingleStep(100)
        self.TextProcessingChunkSizeSpinBox.setObjectName("TextProcessingChunkSizeSpinBox")
        self.label_11 = QtWidgets.QLabel(self.TextProcessingFrame)
        self.label_11.setGeometry(QtCore.QRect(10, 75, 101, 26))
        self.label_11.setObjectName("label_11")
        self.TextProcessingChunkOverlapSpinBox = QtWidgets.QSpinBox(self.TextProcessingFrame)
        self.TextProcessingChunkOverlapSpinBox.setGeometry(QtCore.QRect(140, 75, 91, 24))
        self.TextProcessingChunkOverlapSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TextProcessingChunkOverlapSpinBox.setMaximum(200)
        self.TextProcessingChunkOverlapSpinBox.setSingleStep(10)
        self.TextProcessingChunkOverlapSpinBox.setObjectName("TextProcessingChunkOverlapSpinBox")
        self.TextProcessingLoadPushButton = QtWidgets.QPushButton(self.TextProcessingFrame)
        self.TextProcessingLoadPushButton.setGeometry(QtCore.QRect(10, 110, 101, 26))
        self.TextProcessingLoadPushButton.setObjectName("TextProcessingLoadPushButton")
        self.TextProcessingSaveButton = QtWidgets.QPushButton(self.TextProcessingFrame)
        self.TextProcessingSaveButton.setGeometry(QtCore.QRect(120, 110, 111, 26))
        self.TextProcessingSaveButton.setObjectName("TextProcessingSaveButton")
        self.TextProcessingTitle = QtWidgets.QFrame(self.TextProcessingFrame)
        self.TextProcessingTitle.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.TextProcessingTitle.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.TextProcessingTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TextProcessingTitle.setObjectName("TextProcessingTitle")
        self.label_9 = QtWidgets.QLabel(self.TextProcessingTitle)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.TextProcessingFrame)
        self.EmbeddingModelFrame = QtWidgets.QFrame(self.frame_2)
        self.EmbeddingModelFrame.setMinimumSize(QtCore.QSize(0, 220))
        self.EmbeddingModelFrame.setMaximumSize(QtCore.QSize(16777215, 220))
        self.EmbeddingModelFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.EmbeddingModelFrame.setObjectName("EmbeddingModelFrame")
        self.EmbeddingModelContextTokensSpinBox = QtWidgets.QSpinBox(self.EmbeddingModelFrame)
        self.EmbeddingModelContextTokensSpinBox.setGeometry(QtCore.QRect(140, 80, 91, 24))
        self.EmbeddingModelContextTokensSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.EmbeddingModelContextTokensSpinBox.setMinimum(500)
        self.EmbeddingModelContextTokensSpinBox.setMaximum(9999)
        self.EmbeddingModelContextTokensSpinBox.setSingleStep(500)
        self.EmbeddingModelContextTokensSpinBox.setObjectName("EmbeddingModelContextTokensSpinBox")
        self.label_13 = QtWidgets.QLabel(self.EmbeddingModelFrame)
        self.label_13.setGeometry(QtCore.QRect(10, 115, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.EmbeddingModelThreadsSpinBox = QtWidgets.QSpinBox(self.EmbeddingModelFrame)
        self.EmbeddingModelThreadsSpinBox.setGeometry(QtCore.QRect(140, 115, 91, 24))
        self.EmbeddingModelThreadsSpinBox.setFrame(True)
        self.EmbeddingModelThreadsSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.EmbeddingModelThreadsSpinBox.setMinimum(1)
        self.EmbeddingModelThreadsSpinBox.setMaximum(128)
        self.EmbeddingModelThreadsSpinBox.setObjectName("EmbeddingModelThreadsSpinBox")
        self.label_14 = QtWidgets.QLabel(self.EmbeddingModelFrame)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.EmbeddingModelGPULayersSpinBox = QtWidgets.QSpinBox(self.EmbeddingModelFrame)
        self.EmbeddingModelGPULayersSpinBox.setGeometry(QtCore.QRect(140, 150, 91, 24))
        self.EmbeddingModelGPULayersSpinBox.setStyleSheet("")
        self.EmbeddingModelGPULayersSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.EmbeddingModelGPULayersSpinBox.setObjectName("EmbeddingModelGPULayersSpinBox")
        self.label_15 = QtWidgets.QLabel(self.EmbeddingModelFrame)
        self.label_15.setGeometry(QtCore.QRect(10, 150, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.EmbeddingModelComboBox = QtWidgets.QComboBox(self.EmbeddingModelFrame)
        self.EmbeddingModelComboBox.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.EmbeddingModelComboBox.setObjectName("EmbeddingModelComboBox")
        self.frame_13 = QtWidgets.QFrame(self.EmbeddingModelFrame)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.frame_13.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setObjectName("frame_13")
        self.label_12 = QtWidgets.QLabel(self.frame_13)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.EmbeddingModelLoadPushButton = QtWidgets.QPushButton(self.EmbeddingModelFrame)
        self.EmbeddingModelLoadPushButton.setGeometry(QtCore.QRect(10, 185, 221, 26))
        self.EmbeddingModelLoadPushButton.setObjectName("EmbeddingModelLoadPushButton")
        self.verticalLayout_2.addWidget(self.EmbeddingModelFrame)
        self.VectorDataBaseFrame = QtWidgets.QFrame(self.frame_2)
        self.VectorDataBaseFrame.setMinimumSize(QtCore.QSize(0, 235))
        self.VectorDataBaseFrame.setMaximumSize(QtCore.QSize(16777215, 235))
        self.VectorDataBaseFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VectorDataBaseFrame.setObjectName("VectorDataBaseFrame")
        self.VectorDataBaseStopPushButton = QtWidgets.QPushButton(self.VectorDataBaseFrame)
        self.VectorDataBaseStopPushButton.setGeometry(QtCore.QRect(120, 40, 111, 26))
        self.VectorDataBaseStopPushButton.setObjectName("VectorDataBaseStopPushButton")
        self.VectorDataBaseProcessPushButton = QtWidgets.QPushButton(self.VectorDataBaseFrame)
        self.VectorDataBaseProcessPushButton.setGeometry(QtCore.QRect(10, 40, 101, 26))
        self.VectorDataBaseProcessPushButton.setObjectName("VectorDataBaseProcessPushButton")
        self.VectorDataBaseProgressBar = QtWidgets.QProgressBar(self.VectorDataBaseFrame)
        self.VectorDataBaseProgressBar.setGeometry(QtCore.QRect(10, 80, 221, 26))
        self.VectorDataBaseProgressBar.setProperty("value", 13)
        self.VectorDataBaseProgressBar.setTextVisible(False)
        self.VectorDataBaseProgressBar.setObjectName("VectorDataBaseProgressBar")
        self.VEctorDataBaseSavePushButton = QtWidgets.QPushButton(self.VectorDataBaseFrame)
        self.VEctorDataBaseSavePushButton.setGeometry(QtCore.QRect(120, 120, 111, 26))
        self.VEctorDataBaseSavePushButton.setObjectName("VEctorDataBaseSavePushButton")
        self.VectorDataBaseLoadPushButton = QtWidgets.QPushButton(self.VectorDataBaseFrame)
        self.VectorDataBaseLoadPushButton.setGeometry(QtCore.QRect(10, 120, 101, 26))
        self.VectorDataBaseLoadPushButton.setObjectName("VectorDataBaseLoadPushButton")
        self.label_17 = QtWidgets.QLabel(self.VectorDataBaseFrame)
        self.label_17.setGeometry(QtCore.QRect(10, 161, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.VectorDataBaseSearchKSpinBox = QtWidgets.QSpinBox(self.VectorDataBaseFrame)
        self.VectorDataBaseSearchKSpinBox.setGeometry(QtCore.QRect(140, 160, 91, 24))
        self.VectorDataBaseSearchKSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.VectorDataBaseSearchKSpinBox.setMinimum(1)
        self.VectorDataBaseSearchKSpinBox.setMaximum(20)
        self.VectorDataBaseSearchKSpinBox.setObjectName("VectorDataBaseSearchKSpinBox")
        self.label_18 = QtWidgets.QLabel(self.VectorDataBaseFrame)
        self.label_18.setGeometry(QtCore.QRect(10, 200, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.VectorDataBaseExtendSpinBox = QtWidgets.QSpinBox(self.VectorDataBaseFrame)
        self.VectorDataBaseExtendSpinBox.setGeometry(QtCore.QRect(140, 200, 91, 24))
        self.VectorDataBaseExtendSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.VectorDataBaseExtendSpinBox.setMaximum(5)
        self.VectorDataBaseExtendSpinBox.setObjectName("VectorDataBaseExtendSpinBox")
        self.VectorDataBaseTitle = QtWidgets.QFrame(self.VectorDataBaseFrame)
        self.VectorDataBaseTitle.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.VectorDataBaseTitle.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.VectorDataBaseTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VectorDataBaseTitle.setObjectName("VectorDataBaseTitle")
        self.label_16 = QtWidgets.QLabel(self.VectorDataBaseTitle)
        self.label_16.setGeometry(QtCore.QRect(10, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.VectorDataBaseFrame)
        self.ModelDownloadingFrame = QtWidgets.QFrame(self.frame_2)
        self.ModelDownloadingFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.ModelDownloadingFrame.setMaximumSize(QtCore.QSize(16777215, 160))
        self.ModelDownloadingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ModelDownloadingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ModelDownloadingFrame.setObjectName("ModelDownloadingFrame")
        self.ModelDownloadingTitle = QtWidgets.QFrame(self.ModelDownloadingFrame)
        self.ModelDownloadingTitle.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.ModelDownloadingTitle.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.ModelDownloadingTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ModelDownloadingTitle.setObjectName("ModelDownloadingTitle")
        self.label_20 = QtWidgets.QLabel(self.ModelDownloadingTitle)
        self.label_20.setGeometry(QtCore.QRect(10, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.ModelDownloadingLineEdit = QtWidgets.QLineEdit(self.ModelDownloadingFrame)
        self.ModelDownloadingLineEdit.setGeometry(QtCore.QRect(12, 40, 211, 27))
        self.ModelDownloadingLineEdit.setObjectName("ModelDownloadingLineEdit")
        self.ModelDownloadingDownloadPushButton = QtWidgets.QPushButton(self.ModelDownloadingFrame)
        self.ModelDownloadingDownloadPushButton.setGeometry(QtCore.QRect(10, 80, 101, 26))
        self.ModelDownloadingDownloadPushButton.setObjectName("ModelDownloadingDownloadPushButton")
        self.ModelDownloadingProgressBar = QtWidgets.QProgressBar(self.ModelDownloadingFrame)
        self.ModelDownloadingProgressBar.setGeometry(QtCore.QRect(10, 120, 216, 26))
        self.ModelDownloadingProgressBar.setProperty("value", 22)
        self.ModelDownloadingProgressBar.setTextVisible(False)
        self.ModelDownloadingProgressBar.setObjectName("ModelDownloadingProgressBar")
        self.ModelDownloadingStopPushButton = QtWidgets.QPushButton(self.ModelDownloadingFrame)
        self.ModelDownloadingStopPushButton.setGeometry(QtCore.QRect(125, 80, 101, 26))
        self.ModelDownloadingStopPushButton.setObjectName("ModelDownloadingStopPushButton")
        self.verticalLayout_2.addWidget(self.ModelDownloadingFrame)
        self.LanguageFrame = QtWidgets.QFrame(self.frame_2)
        self.LanguageFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.LanguageFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.LanguageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LanguageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LanguageFrame.setObjectName("LanguageFrame")
        self.LanguageTitle = QtWidgets.QFrame(self.LanguageFrame)
        self.LanguageTitle.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.LanguageTitle.setStyleSheet("QFrame {\n"
"    border-radius : 5px;\n"
"    border-bottom-left-radius : 0px;\n"
"    border-bottom-right-radius : 0px;\n"
"    background-color : black;\n"
"    color : white;\n"
"}")
        self.LanguageTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LanguageTitle.setObjectName("LanguageTitle")
        self.label_21 = QtWidgets.QLabel(self.LanguageTitle)
        self.label_21.setGeometry(QtCore.QRect(10, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.LanguageComboBox = QtWidgets.QComboBox(self.LanguageFrame)
        self.LanguageComboBox.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.LanguageComboBox.setObjectName("LanguageComboBox")
        self.verticalLayout_2.addWidget(self.LanguageFrame)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setText(_translate("MainWindow", "Simple RAG"))
        self.label_2.setText(_translate("MainWindow", "Context tokens"))
        self.label_3.setText(_translate("MainWindow", "Threads"))
        self.label_4.setText(_translate("MainWindow", "GPU Layers"))
        self.AnswerModelLoadPushButton.setText(_translate("MainWindow", "Load"))
        self.label.setText(_translate("MainWindow", "Answer model"))
        self.label_22.setText(_translate("MainWindow", "Generation settings"))
        self.label_5.setText(_translate("MainWindow", "Max tokens"))
        self.label_7.setText(_translate("MainWindow", "Echo"))
        self.label_6.setText(_translate("MainWindow", "Top K"))
        self.label_8.setText(_translate("MainWindow", "Preset"))
        self.label_10.setText(_translate("MainWindow", "Chunk size"))
        self.label_11.setText(_translate("MainWindow", "Chunk overlap"))
        self.TextProcessingLoadPushButton.setText(_translate("MainWindow", "Load"))
        self.TextProcessingSaveButton.setText(_translate("MainWindow", "Save"))
        self.label_9.setText(_translate("MainWindow", "Text processing"))
        self.label_13.setText(_translate("MainWindow", "Threads"))
        self.label_14.setText(_translate("MainWindow", "Context tokens"))
        self.label_15.setText(_translate("MainWindow", "GPU Layers"))
        self.label_12.setText(_translate("MainWindow", "Embedding model"))
        self.EmbeddingModelLoadPushButton.setText(_translate("MainWindow", "Load"))
        self.VectorDataBaseStopPushButton.setText(_translate("MainWindow", "Stop"))
        self.VectorDataBaseProcessPushButton.setText(_translate("MainWindow", "Process"))
        self.VEctorDataBaseSavePushButton.setText(_translate("MainWindow", "Save"))
        self.VectorDataBaseLoadPushButton.setText(_translate("MainWindow", "Load"))
        self.label_17.setText(_translate("MainWindow", "Search K"))
        self.label_18.setText(_translate("MainWindow", "Extend"))
        self.label_16.setText(_translate("MainWindow", "Vector data base"))
        self.label_20.setText(_translate("MainWindow", "Model downloading"))
        self.ModelDownloadingDownloadPushButton.setText(_translate("MainWindow", "Download"))
        self.ModelDownloadingStopPushButton.setText(_translate("MainWindow", "Stop"))
        self.label_21.setText(_translate("MainWindow", "Language"))
import ico_res_rc
